[package]
name = "searchify"
version = "0.1.0"
authors = ["Kyle Phelps <kphelps@salsify.com>"]
edition = "2018"

[dependencies]
actix = "*"
actix_derive = "*"
actix-web = "*"
actix-web-async-await = "*"
clap = "*"
env_logger = "*"
grpcio = "*"
failure = "*"
futures = "*"
futures-cpupool = "*"
log = "*"
protobuf = "*"
rand = "*"
raft = "*"
serde = "*"
serde_derive = "*"
tantivy = "*"
tarpc = "*"
tokio = "*"
tokio-async-await = "*"
uuid = "*"

[build-dependencies]
protoc-grpcio = "*"