{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Volume",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(searchify_web_request_duration_seconds_count[1m])",
     "legendFormat": "Node {{node}}"
    }
   ]
  },
  {
   "title": "p99 Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(searchify_web_request_duration_seconds_bucket[1m]))",
     "legendFormat": "Node {{node}}"
    }
   ]
  },
  {
   "title": "p99 gRPC Client Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(searchify_grpc_client_duration_bucket[1m]))",
     "legendFormat": "{{node}}/{{type}}"
    }
   ]
  },
  {
   "title": "p99 gRPC Server Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(searchify_grpc_server_duration_bucket[1m]))",
     "legendFormat": "{{node}}/{{type}}"
    }
   ]
  },
  {
   "title": "Client gRPC Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(searchify_grpc_client_errors[1m])",
     "legendFormat": "{{node}}/{{type}}"
    }
   ]
  },
  {
   "title": "Server gRPC Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(searchify_grpc_server_errors[1m])",
     "legendFormat": "{{node}}/{{type}}"
    }
   ]
  }
 ]
}