advertised_host = "localhost"
storage_root = "./data_4"
node_id = 4
port = 11669
seeds = [
  "localhost:11666",
]

[web]
port = 8083

[gossip]
port = 11769
bootstrap = [
  "localhost:11766",
  "localhost:11767",
]