storage_root = "./data_2"
node_id = 2
port = 11667
seeds = [
  "localhost:11666",
  "localhost:11668",
]

[web]
port = 8081

[gossip]
port = 11767
bootstrap = [
  "http://localhost:11766",
  "http://localhost:11768",
]