storage_root = "./data_3"
node_id = 3
port = 11668
seeds = [
  "localhost:11666",
  "localhost:11667",
]

[web]
port = 8082

[gossip]
port = 11768
bootstrap = [
  "localhost:11766",
  "localhost:11767",
]